### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DHANANJAYhack** [MrAdityaAlok/java-in-termux#6]
I have an essue I got the error msg when is try to check version or run any js file
![Screenshot_2021-01-01-10-20-53-125_com termux](https://user-images.githubusercontent.com/76041399/103433641-0c5a3b00-4c1b-11eb-8c2e-8dfc11c91d89.jpg)

**Comment by MrAdityaAlok** [comment]
was java pre-installed or any before installation failed....?
