### ISSUE TITLE
Error loading shared libraries libpthread.so

### ISSUE THREAD

**Issue by 1stblood** [MrAdityaAlok/java-in-termux#7]
$ java --version
java: error while loading shared libraries: libpthread.so.0: cannot open shared object file: No such file or directory

Linux localhost 4.14.141-g2dd0cee #1 SMP PREEMPT Wed Dec 23 22:17:47 WIB 2020 aarch64 Android

**Comment by MrAdityaAlok** [comment]
Sorry @1stblood  I cannot do anything with JDK 8 working on aarch 64 . It works on some android firmwares and not on some.
I would advice you to use JDK 11 , it is tested and working on very aarch64 device.
